language: node_js
node_js:
  - "node"

install: npm install

before_script:
  - npm install -g gulp-cli

script: gulp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci dashboard
  local_dir: ./build/
  on:
    branch: master